#ifndef GPIO_CONFIG_H
#define GPIO_CONFIG_H

#define HOT_WATER_INLET_VALVE_RELAY_OUTPUT_PIN A1
#define COLD_WATER_INLET_VALVE_RELAY_OUTPUT_PIN A2

#define WATER_DRAIN_VALVE_RELAY_OUTPUT_PIN A3
#define NA_RELAY_OUTPUT_PIN 13

#define CLOCKWISE_SPINNER_POWER_RELAY_OUTPUT_PIN 11
#define ANTICLOCKWISE_SPINNER_POWER_RELAY_OUTPUT_PIN 12

#define LID_INPUT_PIN 2



#endif