#ifndef GPIO_CONFIG_H
#define GPIO_CONFIG_H

#define HOT_WATER_INLET_VALVE_RELAY_OUTPUT_PIN 4
#define COLD_WATER_INLET_VALVE_RELAY_OUTPUT_PIN 5

#define WATER_DRAIN_VALVE_RELAY_OUTPUT_PIN 6
#define NA_RELAY_OUTPUT_PIN 7

#define CLOCKWISE_SPINNER_POWER_RELAY_OUTPUT_PIN 8
#define ANTICLOCKWISE_SPINNER_POWER_RELAY_OUTPUT_PIN 9

#define LID_INPUT_PIN 10



#endif