

#include "washing_machine_routine.hpp"


int DEFAULT_MACHINE_ROUTINE[7][4] = {
   {MACHINE_WAITING_STATE, 1, 0, 0},
   {WATER_FILLING_STATE, 90, 0, 0},
    {WASHER_SPINNING_STATE, 350, 5, 2},
    {CLOTHES_SOAKING_STATE, 350, 0, 0},
    {WATER_DRAINING_STATE, 200, 0, 0},
    {DRYER_STATE, 200, 0, 0},
    {ROUTINE_END_STATE, 5, 0, 0}};

int machine_routines[16][4] = {
    {MACHINE_WAITING_STATE, 1, 0, 0},
    {WATER_FILLING_STATE, 90, 0, 0},
    {WASHER_SPINNING_STATE, 350, 5, 2},
    {CLOTHES_SOAKING_STATE, 350, 0, 0},
    {WATER_DRAINING_STATE, 200, 0, 0},
    {DRYER_STATE, 200, 0, 0},
    {ROUTINE_END_STATE, 5, 0, 0},
    {MACHINE_WAITING_STATE, 1, 0, 0},
    {MACHINE_WAITING_STATE, 1, 0, 0},
    {MACHINE_WAITING_STATE, 1, 0, 0},
    {MACHINE_WAITING_STATE, 1, 0, 0},
    {MACHINE_WAITING_STATE, 1, 0, 0},
    {MACHINE_WAITING_STATE, 1, 0, 0},
    {MACHINE_WAITING_STATE, 1, 0, 0},
    {MACHINE_WAITING_STATE, 1, 0, 0},
    {MACHINE_WAITING_STATE, 1, 0, 0}};